### ISSUE TITLE
Reconfigure airbase kiska base

### ISSUE THREAD

**Issue by chiefshot** [KISKA-Factory/Chongo-Mission-1.chongo#3]
## Description
With the Kiska base refactor and the remodeling in #2 there are significant changes necessary for the Kiska base implementation.

## Acceptance Criteria
- [ ] add US helicopters on pads
- [ ] add US light land vehicles
- [ ] add logistic vehicles
- [ ] add generic civilian vehicles
- [ ] add Chongo land vehicles
- [ ] add US air crew
- [ ] add Chongo guards on posts
- [ ] add US maintenance crew
- [ ] add US SOF on duty
- [ ] add Chongo off duty at barracks
- [ ] add US and Chongo TOC group
- [ ] add Chongo patrols
- [ ] add all animations to bases

**Comment by Ansible2** [comment]
Rolled into #9
