### ISSUE TITLE
Airbase Environment

### ISSUE THREAD

**Issue by Ansible2** [KISKA-Factory/Chongo-Mission-1.chongo#8]
### Area Purpose
- The airbase is used by a SOF team to live and launch missions from with partner forces within the country

### Who Occupies The Area
- A SOF team
- Aviation element with several helicopters including support personnel
- A small contingent of intel and C2 (command and control) personnel 
- Chongo forces

### Tone and Aesthetic
- Well defended
- Austere environment
- Occupied and lived in but also kind of quickly thrown together
- 24 hour operations
- Underfunded (Chongo/general areas) 

## Acceptance Goals
- [x] Backup a version of the current airbase to the Google Drive
- [x] Players can't leave the airbase.
- [x] Objects are local only, simple, and/or have their simulation disabled unless there is a valid reason as to why they can't or shouldn't be.
- [x] Any simulated objects are dynamically simulated unless there is a valid reason why not.
- [x] Layers are properly implemented to separate simulated and static objects.
- [x] Framerate is not substantially degraded in the area.

## Implementation Suggestions
- There should be room to grow the base in later missions so the US presence **shouldn't** feel as large as possible.
- The Chongo's probably won't have many, if any aircraft.
- We need a TOC for players that will likely be a spot they converse with NPCs about missions/the state of the world.
- Bases in Afghanistan are good reference.
- There aviation element should be just transport helicopters.
- To keep players from leaving the area, we could use VR blocks that are transparent to keep them inside.

**Comment by chiefshot** [comment]
Transparent VR blocks cast shadows.
